### ISSUE TITLE
Add header record to exomizer files

### ISSUE THREAD

**Issue by dmolony** [a2-4am/4cade#288]
Given that you lose some of the original meta-data about a compressed file, wouldn't it be useful to add a header record to the new file with those details? Possibly including the flags and other information necessary to decompress it.

Maybe even create a new file type for the compressed file.

**Comment by peterferrie** [comment]
The compressed files are intended for TR's use only, so the metadata that we lose (load address and original file size) are known implicitly.  We also know that they're compressed because of their location on disk.  The decompression algorithm is the same for all of them (there are no flags to set).  Any header that we could add would be redundant for TR's purpose.

**Comment by dmolony** [comment]
Other programs need to know about these files too. DiskBrowser will not unpack files based on their hard-coded location.
You may also want to compress other files in the future, or change the packing parameters. At some point you will wish you had done this in a more flexible, general-purpose way.
It would only be maybe 8 extra bytes, and it becomes much more useful to everyone.

**Comment by a2-4am** [comment]
Compatibility with third party tools is a non-goal. The uncompressed assets are available in this source repository for anyone who wants to reuse them.

**Comment by dmolony** [comment]
set EXOMIZER=exomizer mem -q -P23 -lnone

I disagree that there are no flags to set.

If you change anything, or compress any other files in the future, I will not be able to identify your packed files. You have the chance to introduce a useful feature for everyone else.

I was requested to support your packed files, which I did. So compatibility is not a non-goal.
