### ISSUE TITLE
Apple II+ with VidHD: not working

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#443]
Total Replay's VidHD/SHR support works fine on a //e, but I'm experiencing issues on a II+...
(I've just added AppleWin support for VidHD/SHR at 1.30.7.0.)

Repro:
- Select Apple II+ model, and insert VidHD card into slot 3.
- Type "LOD" (for Lode Runner) then SPACE.

NB. Running under emulation: AppleWin 1.30.7.0

Results vary depending on the TR build, but all crash in some way...
(Recommended to run under AppleWin's debugger, with `brk all on` - to trap on BRK and invalid opcodes.)

**Total Replay 4.01**
- breaks with invalid opcode $FF at $313

**revision 05 / serial number 20210219** (an image that 4am uploaded to Slack on 2021-11-21)
- "Stop reason: HDD DMA to I/O memory of ROM $C000"
- ...because HDD is trying to read a block to $BEF8, which attempts to write to [$BEF8..$C0F7], ie. the $C0 page causes the trap.

**revision 05 / serial number 20210219** (an image that 4am uploaded to Slack on 2021-12-18)
- BRK at $2CA

**Comment by a2-4am** [comment]
`SHRSingle` saves a pointer to the filename it wants to load, then it calls `BlankSHR` to clear the SHR screen by writing zeroes to $2000-$9FFF/aux. Because auxiliary memory doesn't really exist outside the VidHD, those writes actually go to $2000-$9FFF/main, which clobbers `gSearchStore` at $6000/main, which is where the filename pointer is pointing to. Hilarity does not ensue.
